-- Every wallet mutation is an atomic D1 batch guarded by its observed revision.
CREATE TABLE commerce_wallets (uid TEXT NOT NULL, environment TEXT NOT NULL CHECK(environment IN ('sandbox','production')), points INTEGER NOT NULL CHECK(typeof(points) = 'integer' AND points BETWEEN 0 AND 9007199254740991), revision INTEGER NOT NULL CHECK(typeof(revision) = 'integer' AND revision BETWEEN 0 AND 9007199254740991), PRIMARY KEY(uid, environment));
CREATE TABLE commerce_customers (revenue_cat_id TEXT PRIMARY KEY NOT NULL, uid TEXT NOT NULL);
CREATE TABLE commerce_transactions (tx_key TEXT PRIMARY KEY NOT NULL, uid TEXT NOT NULL, environment TEXT NOT NULL CHECK(environment IN ('sandbox','production')), transaction_id TEXT NOT NULL, product_id TEXT NOT NULL, store TEXT NOT NULL CHECK(store IN ('app_store','play_store')), quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 100), purchased_at INTEGER NOT NULL, refunded INTEGER NOT NULL CHECK(refunded IN (0,1)), points INTEGER NOT NULL CHECK(points > 0), updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(uid, environment) REFERENCES commerce_wallets(uid, environment));
CREATE TABLE commerce_lots (uid TEXT NOT NULL, environment TEXT NOT NULL, tx_key TEXT NOT NULL, remaining INTEGER NOT NULL CHECK(typeof(remaining) = 'integer' AND remaining BETWEEN 0 AND 9007199254740991), purchased_at INTEGER NOT NULL, active INTEGER NOT NULL CHECK(active IN (0,1)), revoked INTEGER NOT NULL CHECK(revoked IN (0,1)), PRIMARY KEY(uid, environment, tx_key), FOREIGN KEY(uid, environment) REFERENCES commerce_wallets(uid, environment), FOREIGN KEY(tx_key) REFERENCES commerce_transactions(tx_key), CHECK(active = (remaining > 0 AND revoked = 0)), CHECK(revoked = 0 OR remaining = 0));
CREATE INDEX commerce_lots_fifo ON commerce_lots(uid, environment, active, purchased_at, tx_key);
CREATE TABLE commerce_redemptions (uid TEXT NOT NULL, environment TEXT NOT NULL, operation_id TEXT NOT NULL, run_id TEXT NOT NULL, tool TEXT NOT NULL CHECK(tool IN ('preview','teleport','revive')), expected_cost INTEGER NOT NULL, context_key TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('ready','applied','refunded')), allocations TEXT NOT NULL CHECK(json_valid(allocations)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, resolved_at TEXT, PRIMARY KEY(uid, environment, operation_id), FOREIGN KEY(uid, environment) REFERENCES commerce_wallets(uid, environment));
CREATE TABLE commerce_revive_reservations (uid TEXT NOT NULL, environment TEXT NOT NULL, run_id TEXT NOT NULL, operation_id TEXT NOT NULL, PRIMARY KEY(uid, environment, run_id), FOREIGN KEY(uid, environment, operation_id) REFERENCES commerce_redemptions(uid, environment, operation_id));
-- This table remains empty: successful guards insert nothing; a failed guard aborts the entire batch.
CREATE TABLE commerce_revision_assertions (matched INTEGER NOT NULL);
CREATE TRIGGER commerce_assert_revision BEFORE INSERT ON commerce_revision_assertions WHEN NEW.matched != 1 BEGIN SELECT RAISE(ABORT, 'commerce_revision_conflict'); END;
